-- Bonus Chow Chow database setup for Supabase
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique check (char_length(nickname) between 1 and 30),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nickname text not null,
  content text,
  image_url text,
  created_at timestamptz not null default now(),
  check (content is not null or image_url is not null)
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create policy "profiles are readable by signed-in users"
on public.profiles for select to authenticated using (true);

create policy "users can create their own profile"
on public.profiles for insert to authenticated with check (auth.uid() = id);

create policy "users can update their own profile"
on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create policy "signed-in users can read messages"
on public.messages for select to authenticated using (true);

create policy "users can send messages as themselves"
on public.messages for insert to authenticated with check (auth.uid() = user_id);

-- Automatically create a profile after signup using the nickname supplied in auth metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, nickname)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'nickname',''), 'New Member')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Storage bucket for chat photos.
insert into storage.buckets (id, name, public)
values ('chat-photos', 'chat-photos', true)
on conflict (id) do nothing;

create policy "signed-in users can upload chat photos"
on storage.objects for insert to authenticated
with check (bucket_id = 'chat-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "anyone can view chat photos"
on storage.objects for select
using (bucket_id = 'chat-photos');

-- Turn on realtime for messages.
alter publication supabase_realtime add table public.messages;
